namespace fsm
{
    public enum FSMEventType
    {
		NONE = 0,
		TOUCH_STARTED = 1,
		TOUCH_MOVED = 2,
		TOUCH_ENDED = 3,
		TOUCH_TAP = 4,
		ON_APPLICATION_PAUSED = 12,
		ON_APPLICATION_RESUMED = 6,
		KEYBOARD_MOVED = 7,
		PLAYER_SHOOT = 8,
		ENEMY_DESTROYED = 9,
		REQUEST_MAIN_MENU = 13,
		PREPARE_MENU = 10,
		ON_APPLICATION_MAIN_MENU = 11,
		REQUEST_PLAY = 14,
		ON_APPLICATION_GAME = 15,
		ON_APPLICATION_PLAYER_SELECTOR = 16,
		REQUEST_PLAYER_NEXT_SKIN = 17,
		REQUEST_PLAYER_PREVIOUS_SKIN = 18,
		REQUEST_PLAYER_SELECTOR = 19,
		REQUEST_GAME_OVER = 20,
		ON_APPLICATION_GAME_OVER = 21,
		PLAYER_DESTROYED = 22,
		REQUEST_PAUSE = 23,
		REQUEST_RESUME = 24,
		PLAYER_COLLECT = 25,
}
}
